'use client';
import Link from 'next/link';
import { FormEvent,useEffect,useState } from 'react';
import { api,ApiError } from '@/lib/api';
type Address={id?:string;recipientName:string;phone:string;addressLine1:string;addressLine2:string;landmark:string;city:string;state:string;postalCode:string;country:string};
type View={addresses:Address[];selection:{boxes:{name:string;quantity:number}[];items:{name:string;quantity:number}[]}};
const empty:Address={recipientName:'',phone:'',addressLine1:'',addressLine2:'',landmark:'',city:'',state:'',postalCode:'',country:'IN'};
const fields:{key:keyof Address;label:string;auto:string;optional?:boolean}[]=[{key:'recipientName',label:'Recipient name',auto:'shipping name'},{key:'phone',label:'Phone number (with country code)',auto:'shipping tel'},{key:'addressLine1',label:'House / flat number and street',auto:'shipping address-line1'},{key:'addressLine2',label:'Apartment / area (optional)',auto:'shipping address-line2',optional:true},{key:'landmark',label:'Landmark (optional)',auto:'off',optional:true},{key:'city',label:'City',auto:'shipping address-level2'},{key:'state',label:'State / region',auto:'shipping address-level1'},{key:'postalCode',label:'PIN / postal code',auto:'shipping postal-code'},{key:'country',label:'Country code (e.g. IN)',auto:'shipping country'}];
export default function DeliveryCheckout(){
 const [view,setView]=useState<View|null>(null),[address,setAddress]=useState<Address>(empty),[review,setReview]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
 function failure(e:unknown){if(e instanceof ApiError&&e.status===401){window.location.replace('/account?next=%2Fcheckout');return;}setError(e instanceof Error?e.message:'Unable to load checkout. Please retry.');}
 useEffect(()=>{let active=true;api<View>('/auth/gift/checkout').then(v=>{if(active){setView(v);if(v.addresses[0])setAddress(v.addresses[0]);}}).catch(e=>{if(active)failure(e);});return()=>{active=false;};},[retry]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const latest=await api<View>('/auth/gift/checkout');setView(latest);const result=await api<{address:Address}>('/auth/gift/address','POST',address);setAddress(result.address);setReview(true);}catch(e){failure(e);}finally{setBusy(false);}}
 return <section className="section delivery-checkout"><p className="eyebrow">YOUR GIFT, ALMOST THERE</p><h1>{review?'Review your gift.':'Where should we send it?'}</h1><p className="checkout-steps">1. Signed in <span>→</span> 2. Delivery <span>→</span> 3. Review & payment</p>{error&&<div className="notice" role="alert">{error} <button className="text-link" onClick={()=>{setError('');setRetry(n=>n+1);}}>Retry</button></div>}{!view?<p role="status">{error?'Checkout could not be loaded.':'Checking your account and gift…'} <Link href="/cart">Back to bag</Link></p>:<div className="delivery-layout"><div>{review?<><h2>Delivery details</h2><address>{address.recipientName}<br/>{address.addressLine1}<br/>{address.addressLine2&&<>{address.addressLine2}<br/></>}{address.landmark&&<>{address.landmark}<br/></>}{address.city}, {address.state} {address.postalCode}<br/>{address.country}<br/>{address.phone}</address><button className="text-link" onClick={()=>setReview(false)}>Edit delivery details</button><div className="notice" role="status"><strong>Delivery details saved to your account.</strong><p>These gift selections do not have confirmed selling prices and stock yet. A final total, including delivery and tax, is needed before payment can open.</p><p>No order has been placed or payment taken.</p></div><Link className="button" href="/cart">Back to your gift</Link></>:<form className="delivery-form" onSubmit={submit}><h2>Delivery details</h2>{view.addresses.length>0&&<label>Saved address<select value={address.id||''} onChange={e=>setAddress(view.addresses.find(a=>a.id===e.target.value)||empty)}><option value="">Add a new address</option>{view.addresses.map(a=><option key={a.id} value={a.id}>{a.recipientName} — {a.city}, {a.postalCode}</option>)}</select></label>}<div className="delivery-fields">{fields.map(f=><label key={f.key}>{f.label}<input name={f.key} value={address[f.key]||''} onChange={e=>setAddress({...address,[f.key]:e.target.value})} autoComplete={f.auto} required={!f.optional} maxLength={f.key==='country'?2:f.key==='phone'?25:250} type={f.key==='phone'?'tel':'text'} placeholder={f.key==='phone'?'+91 9876543210':undefined}/></label>)}</div><p className="draft-disclosure">We save this address to your account for checkout. Delivery availability is confirmed with the final order.</p><button className="button" disabled={busy}>{busy?'Saving…':'Save & review gift →'}</button></form>}</div><aside className="delivery-summary"><h2>Your selection</h2>{[...view.selection.boxes,...view.selection.items].map((row,i)=><div key={i}><span>{row.name}</span><span>× {row.quantity}</span></div>)}<Link className="text-link" href="/cart">Edit your bag →</Link><p className="draft-disclosure">Final total pending confirmation.</p></aside></div>}</section>;
}
