'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ShoppingBag, Trash2 } from 'lucide-react';
import { api, cartMutation } from '@/lib/api';
import { CartItem, money } from '@/lib/types';
type DisplayItem = CartItem & { name: string; slug?: string; variantName?: string; unitPrice: number | null; currency: string; available: boolean };
export default function LegacyCart() {
 const [items,setItems]=useState<DisplayItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await api<{data:{items:DisplayItem[]}}>('/cart');setItems(r.data.items);}catch(e){setError(e instanceof Error?e.message:'Unable to load your bag.');}finally{setLoading(false);}}
 useEffect(()=>{let alive=true;api<{data:{items:DisplayItem[]}}>('/cart').then(r=>{if(alive)setItems(r.data.items);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[]);
 async function update(item:CartItem,quantity:number){setBusy(true);setError('');try{const path=`/cart/items/${encodeURIComponent(item.variantSku||item.productId)}`;await cartMutation(quantity===0?'DELETE':'PATCH',path,quantity?{quantity}:undefined);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to update your bag.');}finally{setBusy(false);}}
 return <section className="section cart-page"><p className="eyebrow">YOUR THOUGHTFUL PICKS</p><h1>A bag full of good things.</h1>{loading?<p role="status">Loading your bag…</p>:error?<div role="alert" className="notice"><p>{error}</p><button className="text-link" onClick={load}>Try again</button></div>:null}{!loading&&!error&&items.length===0?<div className="empty"><ShoppingBag size={40} strokeWidth={1}/><h2>Your next great gift is waiting.</h2><p>Explore the collection and add something thoughtful.</p><Link className="button" href="/shop">Find a gift</Link></div>:items.length>0&&<div className="cart-layout"><div>{items.map(item=><article className="cart-row" key={`${item.productId}:${item.variantSku||''}`}><div><p className="eyebrow">GIFT IN YOUR BAG</p><h3>{item.slug?<Link href={`/products/${item.slug}`}>{item.name}</Link>:item.name}</h3>{item.variantName&&<p>{item.variantName}</p>}<span className="muted">{item.unitPrice===null?'Price unavailable':money(item.unitPrice,item.currency)}{!item.available?' · Currently unavailable':''}</span></div><div className="quantity"><button aria-label="Decrease quantity" disabled={busy||item.quantity<=1} onClick={()=>update(item,item.quantity-1)}>−</button><span>{item.quantity}</span><button aria-label="Increase quantity" disabled={busy} onClick={()=>update(item,item.quantity+1)}>+</button></div><button className="icon" aria-label="Remove gift" disabled={busy} onClick={()=>update(item,0)}><Trash2 size={18}/></button></article>)}</div><aside className="summary"><h2>Your gift bag</h2><p>{items.reduce((n,i)=>n+i.quantity,0)} items selected</p><p>Final prices, delivery and taxes will be confirmed before payment.</p><Link className="button" href="/checkout">Checkout information →</Link><Link className="text-link" href="/shop">Continue exploring</Link></aside></div>}</section>;
}
