export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || '/api/v1';

export const GIFT_BOX_TYPES = {
  CLASSICS: {
    type: 'classics',
    name: 'The Classics',
    subtitle: 'Timeless luxury treats in signature packaging',
    surcharge: 0,
    heroImage: '/images/Category_image/Classics/thumb.png',
  },
  PREMIUM_VELVET: {
    type: 'premium-velvet',
    name: 'Premium Velvet',
    subtitle: 'Rich velvet chest with gold embossed details',
    surcharge: 499,
    heroImage: '/images/Category_image/premium_velvet/thumb.jpeg',
  },
  ROYALE_TIN: {
    type: 'royale-tin',
    name: 'Royale Tin Tin',
    subtitle: 'Ornate heirloom green & gold metallic tin',
    surcharge: 799,
    heroImage: '/images/Category_image/Royale_tin_tin/thumb.jpeg',
  },
};

export const SUBCATEGORIES = [
  { id: 'all', label: 'All Products' },
  { id: 'classics', label: 'Classics' },
  { id: 'premium-velvet', label: 'Premium Velvet' },
  { id: 'royale-tin', label: 'Royale Tin Tin' },
  { id: 'candles', label: 'Candles & Decor' },
  { id: 'wooden-trays', label: 'Wooden Trays' },
  { id: 'resin-art', label: 'Resin Art' },
  { id: 'keepsake-boxes', label: 'Keepsake Boxes' },
];

export const CATALOG_PRODUCTS = [
  {
    _id: 'cih_1',
    name: 'Velvet-Lined Wooden Keepsake Tray (Small)',
    segmentId: 'crafted-in-house',
    subCategoryId: 'wooden-trays',
    segmentName: 'CRAFTED IN-HOUSE',
    basePrice: 129900,
    image: '/images/Product_images/CRAFTED IN-HOUSE/keepsake_small.png',
    description: { short: 'Handcrafted wooden tray with lush velvet lining.' },
  },
  {
    _id: 'cih_2',
    name: 'Hand-Poured Soy Candle 220g (Amber Jar)',
    segmentId: 'crafted-in-house',
    subCategoryId: 'candles',
    segmentName: 'CRAFTED IN-HOUSE',
    basePrice: 99900,
    image: '/images/Product_images/CRAFTED IN-HOUSE/candle_120.png',
    description: { short: 'Aromatic hand-poured soy candle in amber glass jar.' },
  },
  {
    _id: 'cih_3',
    name: 'Resin Coaster Set of 2 (Brand Colours)',
    segmentId: 'crafted-in-house',
    subCategoryId: 'resin-art',
    segmentName: 'CRAFTED IN-HOUSE',
    basePrice: 59900,
    image: '/images/Product_images/CRAFTED IN-HOUSE/Resin_Coaster_Setof2(Brand Colours).jpg',
    description: { short: 'Artisanal gold-flecked resin coasters.' },
  },
  {
    _id: 'cih_4',
    name: 'Velvet-Lined Luxury Chest (Large)',
    segmentId: 'crafted-in-house',
    subCategoryId: 'keepsake-boxes',
    segmentName: 'CRAFTED IN-HOUSE',
    basePrice: 249900,
    image: '/images/Product_images/CRAFTED IN-HOUSE/velvet-lined_box_large.jpg',
    description: { short: 'Rich velvet chest featuring gold embossed details.' },
  },
  {
    _id: 'cih_5',
    name: 'Embossed Keepsake Frame',
    segmentId: 'crafted-in-house',
    subCategoryId: 'candles',
    segmentName: 'CRAFTED IN-HOUSE',
    basePrice: 79900,
    image: '/images/Product_images/CRAFTED IN-HOUSE/frame.jpg',
    description: { short: 'Hand-carved solid wood frame with velvet backing.' },
  },
  {
    _id: 'cls_1',
    name: 'The Classics Signature Treat Box',
    segmentId: 'classics',
    subCategoryId: 'classics',
    segmentName: 'CLASSICS',
    basePrice: 149900,
    image: '/images/Category_image/Classics/classic.jpeg',
    description: { short: 'Timeless luxury treats in signature custom packaging.' },
  },
  {
    _id: 'vel_1',
    name: 'Royal Velvet Keepsake Treasure',
    segmentId: 'premium-velvet',
    subCategoryId: 'premium-velvet',
    segmentName: 'PREMIUM VELVET',
    basePrice: 199900,
    image: '/images/Category_image/premium_velvet/vel1.jpeg',
    description: { short: 'Rich velvet chest loaded with gourmet confectioneries.' },
  },
  {
    _id: 'tin_1',
    name: 'Heirloom Metallic Royale Tin Box',
    segmentId: 'royale-tin',
    subCategoryId: 'royale-tin',
    segmentName: 'ROYALE TIN TIN',
    basePrice: 229900,
    image: '/images/Category_image/Royale_tin_tin/tin1.jpeg',
    description: { short: 'Ornate heirloom green & gold metallic tin box.' },
  },
];

export const DEMO_BESTSELLERS = CATALOG_PRODUCTS;
