import type { AdminResource, DisplayField, ResourceDefinition } from './types';

const f = (key: string, label: string, kind: DisplayField['kind'] = 'text', currencyKey?: string): DisplayField => ({ key, label, kind, currencyKey });
const ref = (key: string, label: string, link: AdminResource): DisplayField => ({ key, label, link });
const status = f('status', 'Status', 'status');
const created = f('createdAt', 'Created', 'date');
export const resources: Record<AdminResource, ResourceDefinition> = {
  orders: { key: 'orders', title: 'Orders', singular: 'Order', description: 'Review purchases, payment confirmation and fulfilment together.', permission: 'orders.read', writePermission: 'orders.update', search: 'Order number', columns: ['orderNumber', 'status', 'paymentStatus', 'pricing.grandTotalMinor', 'createdAt'], statuses: ['CREATED', 'PAYMENT_PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED'], fields: [f('orderNumber', 'Order number'), status, f('paymentStatus', 'Payment', 'status'), f('fulfillmentStatus', 'Fulfilment', 'status'), ref('customerId', 'Customer', 'customers'), f('pricing.grandTotalMinor', 'Order total', 'money', 'pricing.currency'), f('pricing.subtotalMinor', 'Subtotal', 'money', 'pricing.currency'), f('pricing.discountMinor', 'Discount', 'money', 'pricing.currency'), f('pricing.shippingMinor', 'Shipping', 'money', 'pricing.currency'), f('pricing.taxMinor', 'Tax', 'money', 'pricing.currency'), created, f('confirmedAt', 'Confirmed', 'date'), f('shippedAt', 'Shipped', 'date'), f('deliveredAt', 'Delivered', 'date'), f('cancelledAt', 'Cancelled', 'date')] },
  customers: { key: 'customers', title: 'Customers', singular: 'Customer', description: 'A customer’s contact details and permission-scoped purchase history.', permission: 'customers.read', search: 'Name or email prefix', columns: ['firstName', 'email', 'status', 'lastOrderAt'], statuses: ['ACTIVE', 'INACTIVE', 'BLOCKED'], fields: [f('firstName', 'First name'), f('lastName', 'Last name'), f('email', 'Email'), f('phone', 'Phone'), status, f('lastOrderAt', 'Last order', 'date'), created] },
  products: { key: 'products', title: 'Products', singular: 'Product', description: 'Manage the saleable catalogue. Storefront preview images are separate.', permission: 'products.read', writePermission: 'products.update', create: true, edit: true, search: 'Name or slug prefix', columns: ['name', 'slug', 'status', 'brand'], statuses: ['DRAFT', 'ACTIVE', 'ARCHIVED'], fields: [f('name', 'Name'), f('slug', 'Slug'), status, f('brand', 'Brand'), f('shortDescription', 'Short description'), f('description', 'Description'), f('categoryIds', 'Category IDs'), f('tags', 'Tags'), created, f('updatedAt', 'Updated', 'date')] },
  variants: { key: 'variants', title: 'Variants', singular: 'Variant', description: 'Sellable SKUs, prices and attributes linked to a product.', permission: 'products.read', writePermission: 'products.update', create: true, edit: true, search: 'SKU or name prefix', columns: ['sku', 'name', 'priceMinor', 'status'], statuses: ['ACTIVE', 'INACTIVE'], fields: [f('sku', 'SKU'), f('name', 'Name'), ref('productId', 'Product', 'products'), f('priceMinor', 'Price', 'money', 'currency'), f('compareAtPriceMinor', 'Compare-at price', 'money', 'currency'), f('weightGrams', 'Weight (grams)', 'number'), status, created] },
  categories: { key: 'categories', title: 'Categories', singular: 'Category', description: 'Organise real products into clear catalogue categories.', permission: 'products.read', writePermission: 'products.create', create: true, search: 'Name or slug prefix', columns: ['name', 'slug', 'status', 'sortOrder'], statuses: ['ACTIVE', 'INACTIVE'], fields: [f('name', 'Name'), f('slug', 'Slug'), f('description', 'Description'), ref('parentId', 'Parent category', 'categories'), status, f('sortOrder', 'Sort order', 'number'), created] },
  inventory: { key: 'inventory', title: 'Inventory', singular: 'Stock record', description: 'Review availability and make reasoned, recorded stock adjustments.', permission: 'inventory.read', writePermission: 'inventory.adjust', search: 'SKU prefix', columns: ['sku', 'availableQuantity', 'reservedQuantity', 'status'], statuses: ['IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'DISABLED'], fields: [f('sku', 'SKU'), ref('variantId', 'Variant', 'variants'), f('availableQuantity', 'Available', 'number'), f('reservedQuantity', 'Reserved', 'number'), f('lowStockThreshold', 'Low stock threshold', 'number'), status, f('updatedAt', 'Updated', 'date')] },
  payments: { key: 'payments', title: 'Payments', singular: 'Payment', description: 'Read provider-confirmed payment records. Payment status is never manually set here.', permission: 'payments.read', search: 'Provider order or payment ID prefix', columns: ['providerPaymentId', 'provider', 'amountMinor', 'status', 'paidAt'], statuses: ['CREATED', 'PENDING', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED'], fields: [f('provider', 'Provider'), f('providerOrderId', 'Provider order'), f('providerPaymentId', 'Provider payment'), ref('orderId', 'Order', 'orders'), ref('customerId', 'Customer', 'customers'), f('amountMinor', 'Amount', 'money', 'currency'), status, f('paidAt', 'Paid at', 'date'), created] },
  refunds: { key: 'refunds', title: 'Refunds', singular: 'Refund', description: 'Review requested and provider-confirmed refunds without changing financial history.', permission: 'refunds.read', capability: 'refunds', search: 'Provider refund ID prefix', columns: ['providerRefundId', 'amountMinor', 'status', 'requestedAt'], statuses: ['REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED'], fields: [ref('orderId', 'Order', 'orders'), ref('paymentId', 'Payment', 'payments'), ref('customerId', 'Customer', 'customers'), f('provider', 'Provider'), f('providerRefundId', 'Provider refund'), f('amountMinor', 'Amount', 'money', 'currency'), status, f('reason', 'Reason'), f('requestedAt', 'Requested', 'date'), f('completedAt', 'Completed', 'date')] },
  invoices: { key: 'invoices', title: 'Invoices', singular: 'Invoice', description: 'Immutable billing snapshots. Document availability is shown separately.', permission: 'invoices.read', capability: 'invoices', search: 'Invoice number prefix', columns: ['invoiceNumber', 'grandTotalMinor', 'status', 'issuedAt'], statuses: ['DRAFT', 'ISSUED', 'VOID'], fields: [f('invoiceNumber', 'Invoice number'), ref('orderId', 'Order', 'orders'), ref('customerId', 'Customer', 'customers'), status, f('grandTotalMinor', 'Total', 'money', 'currency'), f('subtotalMinor', 'Subtotal', 'money', 'currency'), f('discountMinor', 'Discount', 'money', 'currency'), f('shippingMinor', 'Shipping', 'money', 'currency'), f('taxMinor', 'Tax', 'money', 'currency'), f('issuedAt', 'Issued', 'date'), created] },
  coupons: { key: 'coupons', title: 'Coupons', singular: 'Coupon', description: 'Explicit discounts, eligibility dates and usage limits.', permission: 'coupons.read', writePermission: 'coupons.update', create: true, edit: true, search: 'Code prefix', columns: ['code', 'discountType', 'status', 'totalUsed', 'expiresAt'], statuses: ['ACTIVE', 'INACTIVE', 'EXPIRED'], fields: [f('code', 'Code'), f('discountType', 'Discount type'), f('percentageBps', 'Percentage (basis points)', 'number'), f('fixedAmountMinor', 'Fixed discount', 'money', 'currency'), f('minimumOrderMinor', 'Minimum order', 'money', 'currency'), f('maximumDiscountMinor', 'Maximum discount', 'money', 'currency'), f('usageLimit', 'Total usage limit', 'number'), f('perCustomerLimit', 'Per-customer limit', 'number'), f('totalUsed', 'Used', 'number'), status, f('startsAt', 'Starts', 'date'), f('expiresAt', 'Expires', 'date'), created] },
  shipping: { key: 'shipping', title: 'Shipping', singular: 'Shipment', description: 'Shipment history and tracking recorded against orders.', permission: 'shipping.read', capability: 'shipping', search: 'Carrier or tracking prefix', columns: ['trackingNumber', 'carrier', 'status', 'estimatedDeliveryAt'], statuses: ['PENDING', 'PROCESSING', 'SHIPPED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'RETURNED'], fields: [ref('orderId', 'Order', 'orders'), ref('customerId', 'Customer', 'customers'), f('carrier', 'Carrier'), f('trackingNumber', 'Tracking number'), status, f('shippingCostMinor', 'Shipping cost', 'money', 'currency'), f('estimatedDeliveryAt', 'Estimated delivery', 'date'), f('shippedAt', 'Shipped', 'date'), f('deliveredAt', 'Delivered', 'date'), created] },
  notifications: { key: 'notifications', title: 'Notifications', singular: 'Notification', description: 'Delivery attempts and outcomes, with unavailable providers clearly identified.', permission: 'notifications.read', capability: 'notifications', search: 'Notification type prefix', columns: ['type', 'channel', 'status', 'attempts', 'sentAt'], statuses: ['PENDING', 'SENT', 'FAILED'], fields: [f('type', 'Type'), f('channel', 'Channel'), status, f('attempts', 'Attempts', 'number'), ref('customerId', 'Customer', 'customers'), ref('orderId', 'Order', 'orders'), f('sentAt', 'Sent', 'date'), created] },
  'audit-logs': { key: 'audit-logs', title: 'Audit logs', singular: 'Audit event', description: 'A read-only record of privileged actions and operational changes.', permission: 'audit_logs.read', search: 'Action or entity type prefix', columns: ['action', 'entityType', 'actorRole', 'createdAt'], fields: [f('action', 'Action'), f('entityType', 'Entity type'), f('entityId', 'Entity ID'), f('actorId', 'Actor ID'), f('actorRole', 'Actor role'), ref('customerId', 'Customer', 'customers'), f('requestId', 'Request ID'), created] },
  staff: { key: 'staff', title: 'Staff access', singular: 'Staff member', description: 'Owner-managed access to operations. Public registration never grants staff access.', permission: 'admin_users.read', writePermission: 'admin_users.manage', edit: true, search: 'Email prefix', columns: ['email', 'roles', 'active', 'lastLoginAt'], statuses: ['ACTIVE', 'SUSPENDED', 'DISABLED'], fields: [f('email', 'Email'), f('roles', 'Roles'), f('active', 'Access active', 'boolean'), f('permissions', 'Permissions'), f('lastLoginAt', 'Last sign-in', 'date'), created] },
};

export const navItems = [
  { key: 'dashboard', title: 'Overview', permission: 'dashboard.read' },
  ...(['orders', 'customers', 'products', 'inventory', 'payments', 'refunds', 'invoices', 'coupons', 'shipping'] as AdminResource[]).map(key => resources[key]),
  { key: 'analytics', title: 'Analytics', permission: 'analytics.read' },
  resources.notifications, resources['audit-logs'],
  { key: 'settings', title: 'Settings', permission: 'settings.read' },
  resources.staff,
];

export const grantablePermissions = ['dashboard.read', 'orders.read', 'orders.update', 'orders.cancel', 'customers.read', 'products.read', 'products.create', 'products.update', 'inventory.read', 'inventory.adjust', 'payments.read', 'refunds.read', 'refunds.create', 'refunds.approve', 'invoices.read', 'coupons.read', 'coupons.create', 'coupons.update', 'shipping.read', 'shipping.update', 'analytics.read', 'notifications.read', 'audit_logs.read'];
export const createPermission = (resource: AdminResource) => resource === 'coupons' ? 'coupons.create' : 'products.create';
